services:
  # Backend Web Service
  - type: web
    name: mediremind-backend
    env: python
    region: singapore # or oregon, frankfurt etc.
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python worker.py & uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: mediremind-db
          property: connectionString
      - key: GOOGLE_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256

databases:
  # Managed PostgreSQL
  - name: mediremind-db
    databaseName: med_app
    user: med_user
    plan: free
